### ISSUE TITLE
[detail] save not working

### ISSUE THREAD

**Issue by pierr** [KleeGroup/focus-demo#137]

**Comment by pierr** [comment]
This is a vertigo problem parse the id in the url...
```
20150623 15:47:26 [http-bio-8080-exec-7] INFO  ExceptionRestHandlerPlugin - JsonSyntaxException  
com.google.gson.JsonSyntaxException: Error parsing param :Body:[1] on service PUT /movies/{id}
	at io.vertigo.vega.plugins.rest.handler.JsonConverterRestHandlerPlugin.handle(JsonConverterRestHandlerPlugin.java:215)
	at io.vertigo.vega.plugins.rest.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.rest.handler.RateLimitingRestHandlerPlugin.handle(RateLimitingRestHandlerPlugin.java:128)
	at io.vertigo.vega.plugins.rest.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.rest.handler.SessionRestHandlerPlugin.handle(SessionRestHandlerPlugin.java:74)
	at io.vertigo.vega.plugins.rest.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.rest.handler.CorsAllowerRestHandlerPlugin.handle(CorsAllowerRestHandlerPlugin.java:87)
	at io.vertigo.vega.plugins.rest.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.rest.handler.ExceptionRestHandlerPlugin.handle(ExceptionRestHandlerPlugin.java:73)
	at io.vertigo.vega.plugins.rest.handler.HandlerChain.handle(HandlerChain.java:78)
	at io.vertigo.vega.plugins.rest.routesregister.sparkjava.WsRestRoute.handle(WsRestRoute.java:60)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:139)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: ""
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:231)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:95)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:183)
	at com.google.gson.Gson.fromJson(Gson.java:805)
	at com.google.gson.Gson.fromJson(Gson.java:870)
	at com.google.gson.Gson$1.deserialize(Gson.java:127)
	at io.vertigo.vega.rest.engine.GoogleJsonEngine$UiObjectDeserializer.deserialize(GoogleJsonEngine.java:232)
	at io.vertigo.vega.rest.engine.GoogleJsonEngine$UiObjectDeserializer.deserialize(GoogleJsonEngine.java:226)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:805)
	at com.google.gson.Gson.fromJson(Gson.java:770)
	at com.google.gson.Gson.fromJson(Gson.java:719)
	at io.vertigo.vega.rest.engine.GoogleJsonEngine.uiObjectFromJson(GoogleJsonEngine.java:144)
	at io.vertigo.vega.plugins.rest.handler.JsonConverterRestHandlerPlugin.readValue(JsonConverterRestHandlerPlugin.java:393)
	at io.vertigo.vega.plugins.rest.handler.JsonConverterRestHandlerPlugin.handle(JsonConverterRestHandlerPlugin.java:187)
	... 29 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:260)
	at com.google.gson.internal.bind.JsonTreeReader.nextInt(JsonTreeReader.java:197)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
	... 44 more

```
